name: server_driven_ui
description: A simple demo of firestore powered realtime server driven UI 

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.3.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  dots_indicator: ^2.1.0
  expandable_page_view: ^1.0.17
  firebase_auth: ^4.2.2
  firebase_core: ^2.4.0
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  go_router: ^6.0.0
  in_app_review: ^2.0.6
  share_plus: ^6.3.0
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
